# Generated by Django 2.2.6 on 2019-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
